initial push

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -1,93 +1,93 @@
-#
-# BSD 2-Clause License
-#
-# Copyright (c) 2021-2024, Hewlett Packard Enterprise
-# All rights reserved.
-#
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are met:
-#
-# 1. Redistributions of source code must retain the above copyright notice, this
-#    list of conditions and the following disclaimer.
-#
-# 2. Redistributions in binary form must reproduce the above copyright notice,
-#    this list of conditions and the following disclaimer in the documentation
-#    and/or other materials provided with the distribution.
-#
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
-# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
-# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-#
+# #
+# # BSD 2-Clause License
+# #
+# # Copyright (c) 2021-2024, Hewlett Packard Enterprise
+# # All rights reserved.
+# #
+# # Redistribution and use in source and binary forms, with or without
+# # modification, are permitted provided that the following conditions are met:
+# #
+# # 1. Redistributions of source code must retain the above copyright notice, this
+# #    list of conditions and the following disclaimer.
+# #
+# # 2. Redistributions in binary form must reproduce the above copyright notice,
+# #    this list of conditions and the following disclaimer in the documentation
+# #    and/or other materials provided with the distribution.
+# #
+# # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+# # AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+# # IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# # DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
+# # FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+# # DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
+# # SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
+# # CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
+# # OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+# # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# #
 
-name: build_wheels
+# name: build_wheels
 
-on: [push, pull_request]
+# on: [push, pull_request]
 
-env:
-  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
-  HOMEBREW_NO_AUTO_UPDATE: "ON"
-  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
-  HOMEBREW_NO_GITHUB_API: "ON"
-  HOMEBREW_NO_INSTALL_CLEANUP: "ON"
-  CIBW_SKIP: "pp* *i686*" # skip building for PyPy
-  CIBW_ARCHES: x86_64
+# env:
+#   HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
+#   HOMEBREW_NO_AUTO_UPDATE: "ON"
+#   HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
+#   HOMEBREW_NO_GITHUB_API: "ON"
+#   HOMEBREW_NO_INSTALL_CLEANUP: "ON"
+#   CIBW_SKIP: "pp* *i686*" # skip building for PyPy
+#   CIBW_ARCHES: x86_64
 
-jobs:
-  build_wheels:
-    name: Build wheels on ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-22.04, macos-12]
-        gcc_v: [11] # Version of GFortran we want to use.
-    env:
-      FC: gfortran-${{ matrix.gcc_v }}
-      GCC_V: ${{ matrix.gcc_v }}
+# jobs:
+#   build_wheels:
+#     name: Build wheels on ${{ matrix.os }}
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         os: [ubuntu-22.04, macos-12]
+#         gcc_v: [11] # Version of GFortran we want to use.
+#     env:
+#       FC: gfortran-${{ matrix.gcc_v }}
+#       GCC_V: ${{ matrix.gcc_v }}
 
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-python@v2
+#     steps:
+#       - uses: actions/checkout@v2
+#       - uses: actions/setup-python@v2
 
-      - name: Install cibuildwheel
-        run: python -m pip install cibuildwheel>=2.12.3
+#       - name: Install cibuildwheel
+#         run: python -m pip install cibuildwheel>=2.12.3
 
-      - name: Install GFortran Linux
-        if: contains(matrix.os, 'ubuntu')
-        run: |
-          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
-          sudo apt-get update
-          sudo apt-get install -y gcc-${GCC_V} gfortran-${GCC_V}
-          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
-          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V}
-          sudo apt-get install -y libtool automake
+#       - name: Install GFortran Linux
+#         if: contains(matrix.os, 'ubuntu')
+#         run: |
+#           sudo add-apt-repository ppa:ubuntu-toolchain-r/test
+#           sudo apt-get update
+#           sudo apt-get install -y gcc-${GCC_V} gfortran-${GCC_V}
+#           sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
+#           --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V}
+#           sudo apt-get install -y libtool automake
 
-      - name: Install Cmake Linux
-        if: contains(matrix.os, 'ubuntu')
-        run: sudo apt-get install cmake
+#       - name: Install Cmake Linux
+#         if: contains(matrix.os, 'ubuntu')
+#         run: sudo apt-get install cmake
 
-      - name: Install GFortran macOS
-        if: contains(matrix.os, 'macos')
-        run: brew install gcc@${GCC_V} || brew upgrade gcc@${GCC_V} || true
+#       - name: Install GFortran macOS
+#         if: contains(matrix.os, 'macos')
+#         run: brew install gcc@${GCC_V} || brew upgrade gcc@${GCC_V} || true
 
-      - name: Install automake macOS
-        if: contains(matrix.os, 'macos')
-        run: brew install automake || true
+#       - name: Install automake macOS
+#         if: contains(matrix.os, 'macos')
+#         run: brew install automake || true
 
-      - name: Install cmake macOS
-        if: contains(matrix.os, 'macos')
-        run: brew install cmake || true
+#       - name: Install cmake macOS
+#         if: contains(matrix.os, 'macos')
+#         run: brew install cmake || true
 
-      - name: Build wheels
-        run: python -m cibuildwheel --output-dir wheelhouse
+#       - name: Build wheels
+#         run: python -m cibuildwheel --output-dir wheelhouse
 
-      - uses: actions/upload-artifact@v2
-        with:
-          path: ./wheelhouse/*.whl
+#       - uses: actions/upload-artifact@v2
+#         with:
+#           path: ./wheelhouse/*.whl
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,8 +29,10 @@
 name: deploy-release
 
 on:
-  release:
-    types: [published]
+  pull_request:
+  push:
+    branches:
+      - develop
 
 env:
   HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
@@ -41,92 +43,105 @@ env:
   CIBW_SKIP: "pp* *i686*" # skip building for PyPy
   CIBW_ARCHES: x86_64
 
-jobs:
-  build_wheels:
-    name: Build wheels on ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-22.04, macos-12]
-        gcc_v: [11] # Version of GFortran we want to use.
-    env:
-      FC: gfortran-${{ matrix.gcc_v }}
-      GCC_V: ${{ matrix.gcc_v }}
+# jobs:
+#   build_wheels:
+#     name: Build wheels on ${{ matrix.os }}
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         os: [ubuntu-22.04, macos-12]
+#         gcc_v: [11] # Version of GFortran we want to use.
+#     env:
+#       FC: gfortran-${{ matrix.gcc_v }}
+#       GCC_V: ${{ matrix.gcc_v }}
 
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-python@v2
+#     steps:
+#       - uses: actions/checkout@v2
+#       - uses: actions/setup-python@v2
 
-      - name: Install cibuildwheel
-        run: python -m pip install cibuildwheel>=2.12.3
+#       - name: Install cibuildwheel
+#         run: python -m pip install cibuildwheel>=2.12.3
 
-      - name: Install GFortran Linux
-        if: contains(matrix.os, 'ubuntu')
-        run: |
-          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
-          sudo apt-get update
-          sudo apt-get install -y gcc-${GCC_V} gfortran-${GCC_V}
-          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
-          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V}
-          sudo apt-get install -y libtool automake
+#       - name: Install GFortran Linux
+#         if: contains(matrix.os, 'ubuntu')
+#         run: |
+#           sudo add-apt-repository ppa:ubuntu-toolchain-r/test
+#           sudo apt-get update
+#           sudo apt-get install -y gcc-${GCC_V} gfortran-${GCC_V}
+#           sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
+#           --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V}
+#           sudo apt-get install -y libtool automake
 
-      - name: Install Cmake Linux
-        if: contains(matrix.os, 'ubuntu')
-        run: sudo apt-get install cmake
+#       - name: Install Cmake Linux
+#         if: contains(matrix.os, 'ubuntu')
+#         run: sudo apt-get install cmake
 
-      - name: Install GFortran macOS
-        if: contains(matrix.os, 'macos')
-        run: brew install gcc@${GCC_V} || brew upgrade gcc@${GCC_V} || true
+#       - name: Install GFortran macOS
+#         if: contains(matrix.os, 'macos')
+#         run: brew install gcc@${GCC_V} || brew upgrade gcc@${GCC_V} || true
 
-      - name: Install automake macOS
-        if: contains(matrix.os, 'macos')
-        run: brew install automake || true
+#       - name: Install automake macOS
+#         if: contains(matrix.os, 'macos')
+#         run: brew install automake || true
 
-      - name: Install cmake macOS
-        if: contains(matrix.os, 'macos')
-        run: brew install cmake || true
+#       - name: Install cmake macOS
+#         if: contains(matrix.os, 'macos')
+#         run: brew install cmake || true
 
-      - name: Build wheels
-        run: python -m cibuildwheel --output-dir wheelhouse
+#       - name: Build wheels
+#         run: python -m cibuildwheel --output-dir wheelhouse
 
-      - uses: actions/upload-artifact@v2
-        with:
-          path: ./wheelhouse/*.whl
+#       - uses: actions/upload-artifact@v2
+#         with:
+#           path: ./wheelhouse/*.whl
 
-  build_sdist:
-    name: Build source distribution
+#   build_sdist:
+#     name: Build source distribution
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@v2
+
+#       - uses: actions/setup-python@v2
+#         name: Install Python
+#         with:
+#           python-version: '3.9'
+
+#       - name: Build sdist
+#         run: |
+#           sudo apt-get install cmake
+#           python setup.py sdist
+
+#       - uses: actions/upload-artifact@v2
+#         with:
+#           path: dist/*.tar.gz
+
+
+#   upload_pypi:
+#     needs: [build_wheels, build_sdist]
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/download-artifact@v2
+#         with:
+#           name: artifact
+#           path: dist
+
+#       - uses: pypa/gh-action-pypi-publish@master
+#         with:
+#           user: __token__
+#           password: ${{ secrets.PYPI }}
+#           #password: ${{ secrets.TEST_PYPI }}
+#           #repository_url: https://test.pypi.org/legacy/
+
+
+  createPullRequest:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - uses: actions/setup-python@v2
-        name: Install Python
-        with:
-          python-version: '3.9'
-
-      - name: Build sdist
+      - name: Create pull request
         run: |
-          sudo apt-get install cmake
-          python setup.py sdist
-
-      - uses: actions/upload-artifact@v2
-        with:
-          path: dist/*.tar.gz
-
-
-  upload_pypi:
-    needs: [build_wheels, build_sdist]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/download-artifact@v2
-        with:
-          name: artifact
-          path: dist
-
-      - uses: pypa/gh-action-pypi-publish@master
-        with:
-          user: __token__
-          password: ${{ secrets.PYPI }}
-          #password: ${{ secrets.TEST_PYPI }}
-          #repository_url: https://test.pypi.org/legacy/
+          gh pr create -B develop -H master --title 'Merge master into develop' --body 'This PR brings develop up to date with master for release.'
+        env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
